lt:
  locale: lt
  contentDir: "content/lt"
  title: "Dovilė Jakniūnaitė"
  weight: 1
  params:
    description: "Asmeninė svetainė"

en:
  locale: en-us
  contentDir: "content/en"
  title: "Dovilė Jakniūnaitė"
  weight: 2
  params:
    description: "Personal website"

